# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Apply
on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TOFU_ENABLE_STATIC_SENSITIVE: 1
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v4.2.2
      - name: Set-up OpenTofu
        uses: opentofu/setup-opentofu@v1
      - name: Log-in to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Initialise OpenTofu
        id: init
        run: tofu init
        env:
          # https://opentofu.org/docs/cli/config/config-file/#environment-variable-credentials
          TF_TOKEN_backend_api_env0_com: ${{ secrets.ENV0_API_ACCESS_TOKEN }}
          TAILSCALE_AUTH_KEY: ${{secrets.TAILSCALE_AUTH_KEY}}
          # https://opentofu.org/docs/language/values/variables/#environment-variables
          # TF_VAR_env0_org_id: ${{secrets.ENV0_ORG_ID}}
          # TF_VAR_env0_project_id: ${{secrets.ENV0_PROJECT_ID}}
      - name: Apply OpenTofu Definitions
        # if: github.event_name == 'pull_request'
        run: tofu apply
        env:
          TF_TOKEN_backend_api_env0_com: ${{ secrets.ENV0_API_ACCESS_TOKEN }}
          TAILSCALE_AUTH_KEY: ${{secrets.TAILSCALE_AUTH_KEY}}
          # TF_VAR_env0_org_id: ${{secrets.ENV0_ORG_ID}}
          TF_VAR_tailscale_auth_key: ${{secrets.TAILSCALE_AUTH_KEY}}
        