# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
    assignees:
      - AppleGamer22
    reviewers:
      - AppleGamer22
    commit-message:
      prefix: chore
    labels:
      - dependencies

